create table entity_address (
    entity_hotel_id bigint unique,
    id bigint generated by default as identity, 
    address_type varchar(31) not null, 
    door_number varchar(255), 
    floor varchar(255), 
    number varchar(255), 
    state_code varchar(255), 
    street varchar(255), 
    primary key (id)
);

create table entity_attraction (
    close_at time(6) not null, 
    open_at time(6) not null, 
    people_capacity integer not null, 
    id bigint generated by default as identity, 
    name varchar(20) not null, 
    description varchar(500) not null, 
    primary key (id)
);

create table entity_benefit (
    close_at time(6) not null, 
    open_at time(6) not null, 
    id bigint generated by default as identity, 
    name varchar(20) not null, 
    description varchar(500) not null, 
    primary key (id)
);

create table entity_hotel (
    free_rooms integer not null, 
    reserved_rooms integer not null, 
    stars float(53) not null, 
    total_rooms integer not null check (total_rooms>=2), 
    id bigint generated by default as identity, 
    contact_phone varchar(24) not null unique, 
    name varchar(90) not null, 
    primary key (id)
);

create table entity_hotel_attraction (
    entity_attraction_id bigint not null, 
    entity_hotel_id bigint not null
);

create table entity_hotel_benefit (
    entity_benefit_id bigint not null, 
    entity_hotel_id bigint not null
);

create table entity_person (
    age integer not null check (age>=18), 
    number_of_reservations integer not null, 
    address_id bigint unique, 
    id bigint generated by default as identity, 
    name varchar(52) not null, 
    cell_phone_number varchar(255) not null unique, 
    dni varchar(255) not null unique, 
    email varchar(255) not null unique, 
    primary key (id)
);

create table entity_reservation (
    end_at date not null, 
    start_at date not null, 
    total_price numeric(38,2) not null, 
    id bigint generated by default as identity, 
    number_of_nights bigint not null check (number_of_nights>=1), 
    number_of_people bigint not null check ((number_of_people<=4) and (number_of_people>=1)), 
    person_id bigint not null, 
    room_id bigint not null, 
    primary key (id)
);

create table entity_room (
    floor integer not null check (floor>=1), 
    number_of_beds integer not null check ((number_of_beds<=4) and (number_of_beds>=1)), 
    people_capacity integer not null check ((people_capacity<=4) and (people_capacity>=1)), 
    price_per_night numeric(38,2) not null, 
    hotel_id bigint not null, 
    id bigint generated by default as identity, 
    times_booked bigint not null, 
    bed_type varchar(255) not null check (bed_type in (
        'SINGLE',
        'DOUBLE',
        'QUEEN',
        'KING',
        'TWIN')
    ), 
    room_type varchar(255) not null check (room_type in (
        'STANDARD',
        'DELUXE',
        'SUITE',
        'EXECUTIVE',
        'PRESIDENTIAL')
    ), 
    state varchar(255) not null check (state in (
        'OCCUPIED',
        'UNOCCUPIED',
        'BEING_CLEANED',
        'CLEANED',
        'FREE',
        'RESERVED')
    ), 
    primary key (id)
);

create table entity_room_booking_period (
    end_at date not null, 
    start_at date not null, 
    id bigint generated by default as identity, 
    reservation_id bigint not null unique, 
    room_id bigint not null, 
    status varchar(255) not null check (status in (
        'RESERVED',
        'CANCELLED',
        'COMPLETED',
        'BLOCKED')
    ), 
    primary key (id)
);

create table entity_states (
    code varchar(255) not null, 
    country_code varchar(255), 
    subdivision_name varchar(255), 
    primary key (code)
);

alter table if exists entity_address add constraint FKivgrniios7b2khuxcvi2gdf6u foreign key (state_code) references entity_states;
alter table if exists entity_address add constraint FK37s9iec4tog8dqvqn9ag8m01t foreign key (entity_hotel_id) references entity_hotel;
alter table if exists entity_hotel_attraction add constraint FKkbo0dbejefyiuerqr4jswgpgo foreign key (entity_attraction_id) references entity_attraction;
alter table if exists entity_hotel_attraction add constraint FK1y1f7sifyrq8q41n6n94lcmdx foreign key (entity_hotel_id) references entity_hotel;
alter table if exists entity_hotel_benefit add constraint FKh94mu7ikr1fliec0fdt8c6krn foreign key (entity_benefit_id) references entity_benefit;
alter table if exists entity_hotel_benefit add constraint FKihrqbjkveqjyql57u4gavq8qs foreign key (entity_hotel_id) references entity_hotel;
alter table if exists entity_person add constraint FKfbxibk53fgyqbomudklx5kfgj foreign key (address_id) references entity_address;
alter table if exists entity_reservation add constraint FKn90blwl21q349o9rcc661r275 foreign key (person_id) references entity_person;
alter table if exists entity_reservation add constraint FK2kmfms1pg2klmm3i4n140cd47 foreign key (room_id) references entity_room;
alter table if exists entity_room add constraint FKo33av26lhd1aikngyidhuwdou foreign key (hotel_id) references entity_hotel;
alter table if exists entity_room_booking_period add constraint FKax80ywch3hbw1noxrqdniqgxo foreign key (reservation_id) references entity_reservation;
alter table if exists entity_room_booking_period add constraint FK5gxmugbbtsinr5pf5ug5wyh01 foreign key (room_id) references entity_room;